---
  # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
  name: "Container: Image Build"
  on:
    workflow_dispatch:
      inputs:
        publish:
          description: Publish the container to the registry
          required: true
          type: boolean
          default: false

  jobs:
    publish-images:
      name: Publish Image
      permissions:
        contents: write
        packages: write
      runs-on: ubuntu-22.04

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Log into registry ghcr.io
          uses: docker/login-action@v3.3.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3.2.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3.6.1

        - name: Build and publish image
          env:
            DOCKER_BUILDX_ARGS: "--load --cache-from type=gha --cache-to type=gha,mode=max"
          run: |
            make build-image-dirty

        - name: Set image tag
          run: |
            git remote add upstream https://github.com/traefik/traefik.git
            git fetch --tags upstream
            echo "VERSION=$(git describe --tags --match 'v2.*' --exclude '*-' --abbrev=0)" >> $GITHUB_ENV

        - name: Push image
          if: ${{inputs.publish}}
          run: |
            docker tag traefik/traefik ghcr.io/${{ github.repository }}:${VERSION}-${GITHUB_SHA::7}
            docker push ghcr.io/${{ github.repository }}:${VERSION}-${GITHUB_SHA::7}
